# AUTOGENERATED!! DO NOT EDIT
make NOTE_NAME=brave_browser_notes -C brave_browser -f brave_browser.mk --no-print-directory
make NOTE_NAME=c_notes -C c -f c.mk --no-print-directory
make NOTE_NAME=clang-format_notes -C clang-format -f clang-format.mk --no-print-directory
make NOTE_NAME=code_review_notes -C code_review -f code_review.mk --no-print-directory
make NOTE_NAME=counting-numbers-en-ko-hi_notes -C counting-numbers-en-ko-hi -f counting-numbers-en-ko-hi.mk --no-print-directory
make NOTE_NAME=cpp_notes -C cpp -f cpp.mk --no-print-directory
make NOTE_NAME=git_notes -C git -f git.mk --no-print-directory
make NOTE_NAME=linux_notes -C linux -f linux.mk --no-print-directory
make NOTE_NAME=rpi_notes -C rpi -f rpi.mk --no-print-directory
make NOTE_NAME=semaphore_notes -C semaphore -f semaphore.mk --no-print-directory
make NOTE_NAME=vim_notes -C vim -f vim.mk --no-print-directory
make NOTE_NAME=windows_notes -C windows -f windows.mk --no-print-directory
