# AUTOGENERATED!! DO NOT EDIT
make NOTE_NAME=brave_browser_notes -C brave_browser -f brave_browser.mk --no-print-directory
make NOTE_NAME=linux_notes -C linux -f linux.mk --no-print-directory
make NOTE_NAME=rpi_notes -C rpi -f rpi.mk --no-print-directory
