DIRS=	rpi \
		linux

include vars.mk

LOWDOWN_PATH=./lowdown
CSS_PATH=style.css
OBJS= build.sh style.css style.css.map index.html

build: clean script index.html fix_index.html
	@echo -e "$(COLOR_GREEN)DONE$(COLOR_NONE)"

clean:
	@echo -e "$(COLOR_YELLOW)Deleting$(COLOR_NONE) pre-existing (if any) files $(COLOR_BLUE)$(OBJS)$(COLOR_NONE)"
	@rm -f $(OBJS)

script:
	@echo -e "$(COLOR_YELLOW)Generating$(COLOR_NONE) script file $(COLOR_BLUE)build.sh$(COLOR_NONE)"
	@echo "# AUTOGENERATED!! DO NOT EDIT" > build.sh
	@for dirname in $(DIRS); do \
		echo "make -C $${dirname} -f $${dirname}.mk --no-print-directory" >> build.sh ; \
	done
	@chmod +x build.sh
	@./build.sh

index.html: README.md style.css
	@$(LOWDOWN_PATH) -s $< -o $@ -thtml \
	-M author="$(AUTHOR)" \
	-M title="$(TITLE)" \
	-M css="$(CSS_PATH)"
	@echo -e "generated $(COLOR_BLUE)index.html$(COLOR_NONE)"

fix_index.html:
	@sed -i 's/.md/.html/g' index.html

%.css: %.scss
	@echo -e "$(COLOR_YELLOW)Generating$(COLOR_NONE) stylesheet $(COLOR_BLUE)style.css$(COLOR_NONE)"
	@./sass $< $@
