DIRS_UNSORTED=	rpi \
		linux \
		brave_browser

DIRS=$(sort $(DIRS_UNSORTED))

## print sorted DIRS
#$(info $$(DIRS) is [${DIRS}])

include vars.mk

LOWDOWN_PATH=./lowdown
CSS_PATH=style.css
OBJS= build.sh README.md style.css style.css.map index.html

build: clean script README index.html fix_index.html
	@echo -e "$(COLOR_GREEN)DONE$(COLOR_NONE)"

clean:
	@echo -e "$(COLOR_YELLOW)Deleting$(COLOR_NONE) pre-existing (if any) files $(COLOR_BLUE)$(OBJS)$(COLOR_NONE)"
	@rm -f $(OBJS)

script:
	@echo -e "$(COLOR_YELLOW)Generating$(COLOR_NONE) script file $(COLOR_BLUE)build.sh$(COLOR_NONE)"
	@echo "# AUTOGENERATED!! DO NOT EDIT" > build.sh
	@for dirname in $(DIRS); do \
		echo "make -C $${dirname} -f $${dirname}.mk --no-print-directory" >> build.sh ; \
	done
	@chmod +x build.sh
	@./build.sh

README:
	@echo -e "$(COLOR_YELLOW)Generating$(COLOR_NONE) README file $(COLOR_BLUE)README.md$(COLOR_NONE)"
	@echo '# devpogi notes' > README.md
	@echo >> README.md
	@echo '*My learnings on various subjects.*' >> README.md
	@echo >> README.md
	@echo 'List' >> README.md
	@echo >> README.md
	@for dirname in $(DIRS); do \
		echo "- [$${dirname}]($${dirname}/$${dirname}_notes.md)" >> README.md ; \
	done
	@echo >> README.md

index.html: README.md style.css
	@$(LOWDOWN_PATH) $< -o $@.temp -thtml
	@cat html_envelope > index.html
	@cat $@.temp >> index.html
	@echo '</body>' >> index.html
	@echo '</html>' >> index.html
	@rm -f $@.temp
	@echo -e "generated $(COLOR_BLUE)index.html$(COLOR_NONE)"

fix_index.html:
	@sed -i 's/.md/.html/g' index.html

%.css: %.scss
	@echo -e "$(COLOR_YELLOW)Generating$(COLOR_NONE) stylesheet $(COLOR_BLUE)style.css$(COLOR_NONE)"
	@./sass $< $@
